
export const INIT_ARTICLES = 'INIT_ARTICLES';
export const ARTICLE = 'ARTICLE';
export const INIT_MENU = 'INIT_MENU';
export const RESET_LOADING = 'RESET_LOADING';
export const RESET_LOADING_ARTICLE = 'RESET_LOADING_ARTICLE';
export const PUSH_ARTICLES = 'PUSH_ARTICLES';
export const PUSH_ARTICLES_LOW = 'PUSH_ARTICLES_LOW';
export const PUSH_ARTICLES_CUSTOM_VIEW = 'PUSH_ARTICLES_CUSTOM_VIEW';


PUSH_ARTICLES_CUSTOM_VIEW
export const INIT_AUTHORS = 'INIT_AUTHORS';
export const SET_CATEGORY_CODE = 'SET_CATEGORY_CODE';
export const SET_IDFA = 'SET_IDFA';
